# active spring boot profile
spring:
   profiles:
      active: dev   

---

# common - spring configuration
spring:

   # devtools - live reload
   devtools:
      livereload:
         enabled: true

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp



   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 50MB

  

---

# dev profile - spring boot configuration

spring:
   config:
      activate:
         on-profile: dev
      
   # datasource
   datasource:
      username: dv01
      password: 123!
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://34.64.187.132:3306/doki?characterEncoding=utf8
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

---

# production profile - spring boot configuration
spring:
   config:
      activate:
         on-profile: production

   # datasource
   datasource:
      username: webdb
      password: webdb
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/webdb?characterEncoding=utf8
      hikari:
         minimum-idle: 100
         maximum-pool-size: 200

---

# server
server:
   port: 8081
   servlet:
     context-path: /doki
     encoding:
        charset: utf-8
        enabled: true
        force: false
        force-request: false
        force-response: false

---

# mybatis
mybatis:
   configuration: 
      map-underscore-to-camel-case: true
   type-aliases-package: com.douzone.doki.vo
   mapper-locations: mybatis/mappers/*.xml
---

#redis
spring:
   redis:
      port: 6379
      host: 34.64.187.132
      lettuce:
         pool:
            max-active: 10
            max-idle: 10
            min-idle: 2

---

